import js from "@eslint/js";
import tseslint from "typescript-eslint";

export default tseslint.config(
  js.configs.recommended,
  ...tseslint.configs.recommended,
  {
    ignores: [
      "node_modules/**",
      ".wrangler/**",
      "dist/**",
      "worker-configuration.d.ts", // auto-generated by wrangler
    ],
  },
  {
    files: ["test/env.d.ts"],
    rules: {
      // Required empty-interface pattern for cloudflare:test module augmentation
      "@typescript-eslint/no-empty-object-type": "off",
    },
  },
  {
    rules: {
      "@typescript-eslint/no-explicit-any": "warn",
      "@typescript-eslint/no-unused-vars": ["warn", { argsIgnorePattern: "^_" }],
      "no-empty": ["warn", { allowEmptyCatch: true }],
    }
  }
);
